name: Frontend Tests

on:
  push:
  pull_request:

jobs:
  test_front:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"

      - name: Install Dependencies
        run: |
          cd ${{ github.workspace }}/front
          npm install

      - name: Run Tests
        run: |
          cd ${{ github.workspace }}/front
          npm run test:prod

      - name: List files in coverage directory
        run: |
          cd ${{ github.workspace }}/front
          ls -al
          ls -al coverage
          ls -al coverage/bobapp

      - name: Upload Test Results
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: ${{ github.workspace }}/front/coverage

  sonar_front:
    needs: [test_front]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"

      - name: Install Dependencies
        run: |
          cd ${{ github.workspace }}/front
          npm install

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        with:
          fetch-depth: 0
          projectBaseDir: ./front
          extraArgs: |
            -Dsonar.javascript.lcov.reportPaths=coverage/bobapp/lcov.info
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN_FRONT }}

  docker_create_push_front:
    needs: [test_front, sonar_front]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build image and push on Dockerhub
        uses: docker/build-push-action@v4
        with:
          context: ./front
          push: true
          tags: shifff/bobapp_front:${{ github.sha }}
